[workspace]
members = [
    "dynamic-tournament-api",
    "dynamic-tournament-cli",
    "dynamic-tournament-generator",
    "dynamic-tournament-server",
    "dynamic-tournament-test",
    "dynamic-tournament-web",
]
