# An address:port or file path (unix-only) to bind http server to. Use 0.0.0.0 to
# bind to all interfaces.
# Possible values: <ADDR:PORT> | <PATH>
# Default value: 0.0.0.0:80
bind = "0.0.0.0:80"

[log]
# The maximum level of messages logged. Note that using the debug or trace levels
# will produce high amounts of messages. Usage is not recommended for production.
# Possible values: off, error, warn, info, debug, trace
# Default value: warn
level = "warn"

# Whether to emit colorful log messages.
# Possible values: false, true
# Default value: false
color = false

[database]
# The database driver to use 
# Possible values: mysql
# Default value: mysql
driver = "mysql"

# The database host
# Possible values: <ADDR>
# Default value: 127.0.0.1
host = "10.0.0.2"
# The database port
# Possible values: <PORT>
# Default value: 3306
port = 3306

# The database user
# Possible values: <STRING>
# Default value: user 
user = "user"

# The password for the database user
# Possible values: <STRING>
# Default value: 1234
password = "1234"

# The database name
# Possible values: <STRING>
# Default value: dynamictournament
database = "dynamictournament"

# The prefix on tables of the database. Use an empty string to disable.
# Note that the prefix is used literally, there is no additional delimiter.
# Possible values: <STRING>
# Default value: ""
prefix = ""

[authorization]
# Which JWT signing algorithm to use. Don't change this if you don't know what
# that means.
# Possible values: HS256, HS384, HS512
# Default value: HS256
alg = "HS256"

[wordpress]
# The upstream (host) of the wordpress backend. This should include scheme, address
# and port, **but no path or query**. Also note that using the HTTPS scheme requires
# a valid certificate with a trusted chain (.i.e self-signed certificates are invalid).
# Possible values: <SCHEME>://<ADDR:[PORT]>
# Default value: http://hs_gateway:8080
upstream = "http://127.0.0.1:3030"
# The value of the HTTP host header. This header is literally provided in any requests made
# to the wordpress backend. The value may only contain visible ascii characters.
# Possible values: <STRING>
# Default value: beta.hardstuck.local
host = "beta.hardstuck.local"
