[package]
name = "dynamic-tournament-web"
version = "0.2.0"
edition = "2021"

[dependencies]
dynamic-tournament-api = { version = "0.4.0", path = "../dynamic-tournament-api", features = ["local-storage"] }
dynamic-tournament-generator = { version = "0.4.0", path = "../dynamic-tournament-generator", features = ["serde"] }

wee_alloc = "0.4.5"
yew = "0.19.3"
reqwasm = "0.5.0"
serde = { version = "1.0.136", features = ["derive"] }
yew-router = "0.16.0"
gloo-console = "0.2.1"
gloo-timers = "0.2.3"
web-sys = { version = "0.3.56", features = ["Document", "Element", "Node", "Window", "HtmlCollection", "HtmlInputElement"] }
log = "0.4.16"
futures = "0.3.21"
wasm-bindgen-futures = "0.4.30"
yew-agent = "0.1.0"
chrono = { version = "0.4.19", features = ["wasmbind"] }

[profile.release]
debug-assertions = false
opt-level = "z"
lto = "fat"
panic = "abort"
