[package]
name = "dynamic-tournament-api"
version = "0.1.0"
edition = "2021"

[dependencies]
dynamic-tournament-generator = { version = "0.1.0", path = "../dynamic-tournament-generator", features = ["serde"] }

reqwasm = "0.5.0"
serde = { version = "1.0.136", features = ["derive"] }
serde_repr = "0.1.7"
serde_json = "1.0.79"
base64 = "0.13.0"
thiserror = "1.0.30"
