[package]
name = "dynamic-tournament-lang"
version = "0.1.0"
edition = "2021"

publish = false

[dependencies]
dynamic-tournament-generator = { version = "0.4.0", path = "../dynamic-tournament-generator", features = ["serde"] }
