[package]
name = "dynamic-tournament-generator"
version = "0.1.0"
edition = "2021"

[features]
serde = ["dep:serde"]

[dependencies]
thiserror = "1.0.30"
serde = { version = "1.0.136", features = ["derive"], optional = true }
