on:
  push:
    tags:
    - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: make docker
    - run: GIT_TAG=$(git describe --tags --abbrev=0)
    - run: docker tag dynamic-tournament-server:latest ghcr.io/mrgunflame/dynamic-tournament-server:$GIT_TAG
    - run: docker tag dynamic-tournament-server:latest ghcr.io/mrgunflame/dynamic-tournament-server:hs-stable
    - run: echo $GHCR_TOKEN | docker login ghcr.io -u MrGunflame --password-stdin
    - run: docker push ghcr.io/mrgunflame/dynamic-tournament-server:$GIT_TAG
    - run: docker push ghcr.io/mrgunflame/dynamic-tournament-server:hs-stable
