name: Rust

on:
  push:
    branches:
    - "master"
    - "hs-stable"

  pull_request:
    branches:
    - "master"
    - "hs-stable"

env:
  CARGO_TERM_COLOR: always

jobs:
  fmt:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - run: rustup component add rustfmt
    - run: cargo fmt --all -- --check

  clippy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - run: rustup component add clippy
    - run: cargo clippy --all-targets --all-features -- -D warnings

  doc:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - run: RUSTDOCFLAGS="-Dwarnings" cargo doc --no-deps --all-features

  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - run: cargo test --all-features
