name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  fmt:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - run: rustup component add rustfmt
    - run: cargo fmt --all -- --check
    - uses: actions/upload-artifact@v3
      with:
        name: target
        path: target

  clippy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - uses: actions/download-artifact@v3
      with:
        name: target
    - run: rustup component add clippy
    - run: cargo clippy --all-targets --all-features -- -D warnings
    - uses: actions/upload-artifact@v3
      with:
        name: target
        path: target

  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - uses: actions/download-artifact@v3
      with:
        name: target
    - run: cargo test --all-features
